language: node_js
node_js:
- node
before_script:
- npm install -g gulp-cli
script:
- npm run build
before_deploy:
  - cd dist
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: demo/dist/
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: micah.wood@gmail.com
    api_key: $NPM_TOKEN
    on:
      tags: true
      repo: InMoment/angular-expandable-panel-list
      branch: master
