language: node_js
node_js:
- node
before_script:
- npm install -g gulp-cli
script:
- npm run build
env:
  global:
  - secure: FnyCBcHI1ONiNqUJUFlTmXII/ixeoQLdHSm/H2kJsqq3NcV0eHwd7y3UTdoXTWEc6SU0PrK1qASNCo4cWMsJfXa9EbAKDP/yCS/dmgv8bxQ+GxY0/6Ql/KnKJ3GE/VCQc4SOlfiJXDtA4tV9P28rAuAO53ImyEM+DTtztBj7BTB6sIvC5+nD2RLnnIYsQdZhnaKiTk34HZgqWbUwvQ73VSLjMOFTdS/IzmpqbOsk40yjesAphbkmoFKfyaoZ8cJ0T+4lCYJUJ5VnEyyJ7JvO8TAfrVT/mVO5B1ZMEebTu4LxuympowuXTbbXV7ra/A398RkjR7d5JDZOfclmdYd0hStiR208GGin7+ZJVGY6EzmJ6bbEtZ7A/yfsZP5L/fDb8p32kHE1pQ3nbPaU+ub/Ra0UDhblWN76HZyNpfDlSmEaJ0y9POLT/3eg3Y4nlD2RIuPpTcQ92tRiSBgonXkhmCv8XAZQrMa/+cdymBfoLhXmF1KslcpuoCJsDq2Lbrg3ATv7psTpGIJLqQu9Ff6g2CSEzLxTT4knN1t5n0rNL3t5W6hzdHo1PmADYthQYp+50pZCoY5tMfWdy5u8IRf+0NtX574qGMeG+uwvwJFGDeP7+EuvsiEKlbnvJL+qJSiZi5HTqqAqz78IlzNYLKy6FuAIf8Q7S2aJElaSABjiwDU=
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: ./demo/dist/
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: "nathaniel.lord@gmail.com"
    local_dir: ./dist/
    api_key: ""
    on:
      tags: true
      branch: master